sprite_index = get_load_sprite("spr_durian_effect");  //转化额外添加保证触发
image_xscale = 1.8
image_yscale = 1.8
image_speed = 0
can_destroy = false
damage = 0
timer = 0
max_time = 0
grid_pos = 0
target_type = "rotate"
shape = 0